baseurl = "https://www.tzvi.dev"
languageCode = 'en-us'
title = 'Tzvi.dev'
theme = "hugo-coder"
defaultcontentlanguage = "en"

paginate = 20

disqusShortname = "www-tzvi-dev"
googleAnalytics = 'G-8VNBN2DTFH'

[markup.highlight]
style = "github-dark"

[params]
  author = "Tzvi Friedman"
  info = ["Software Engineer & Engineering Manager"]
  description = "Tzvi Friedman's personal website"
  keywords = "devops,software,web development,blog,developer,personal"
  avatarurl = "images/headshot_steve_friedman_circle_clear.png"
  #gravatar = "tadwork@gmail.com"

  faviconSVG = "/favicon.ico"
  favicon_32 = "/favicon-32x32.png"
  favicon_16 = "/favicon-16x16.png"
  manifest = "/site.webmanifest"
  mask_icon = "/safari-pinned-tab.svg"
  touchicon = "/apple-touch-icon.png"

  since = 2008

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  customCSS = ["css/custom.css"]
  #customSCSS = ["scss/custom.scss"]
  #customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.contacts]]
  name = "Github"
  icon = "fa fa-github fa-4x"
  weight = 1
  url = "https://github.com/Tadwork/"
[[params.contacts]]
  name = "LinkedIn"
  icon = "fa fa-linkedin fa-4x"
  weight = 2
  url = "https://www.linkedin.com/in/tzvi-dev/"
[[params.contacts]]
  name = "EMail"
  icon = "fa fa-envelope fa-4x"
  weight = 3
  url = "mailto:tadwork@gmail.com"
# [[params.social]]
#   name = "Twitter"
#   icon = "fa fa-twitter fa-4x"
#   weight = 4
#   url = "tadwork"

# Menu links
# [[menu.main]]
#   name = "Blog"
#   weight = 1
#   url  = "posts/"
[[menu.main]]
  name = "Projects"
  weight = 1
  url = "projects/"
[[menu.main]]
  name = "Posts"
  weight = 1
  url = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"